### ISSUE TITLE
🐛 404 Error on CODE_OF_CONDUCT.md Hyperlink in CONTRIBUTING.md 

### ISSUE THREAD

**Issue by Diana-Paez** [Jaime-A-Perez/To-Do-List-Apple-Ecosystem#6]
---
name: Bug Report
about: Create a report to help us improve
title: '404 Error on CODE_OF_CONDUCT.md Hyperlink in CONTRIBUTING.md'
labels: 'bug'
assignees: Diana-Paez

---

# Bug Report

## Describe the Bug

When attempting to click the hyperlink for `CODE_OF_CONDUCT.md` within the `CONTRIBUTING.md` file, a 404 error page is displayed, indicating that the hyperlink leads to a non-existent page or a misconfiguration of the path to the code of conduct document.

## To Reproduce

1. Go to 'CONTRIBUTING.md'
2. Click on 'CODE_OF_CONDUCT.md hyperlink'
3. Encounter a 404 error page

## Expected Behavior

Upon clicking the `CODE_OF_CONDUCT.md` hyperlink, the browser should navigate to the Code of Conduct document for the project.

## Desktop (please complete the following information):

- Browser [Chrome, Safari]

**Comment by Jaime-A-Perez** [comment]
I have checked the link and confirm that it is broken, causing the 404 error. It appears that the file `CODE_OF_CONDUCT.md` is not in the expected location or the link is misspelled. The corresponding link in `CONTRIBUTING.md` needs to be updated.
